apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongodb
    namespcae: roboshop
    labels:
        project: roboshop
        tier: database
        service: mongodb
spec:
    replicas: 1
    serviceName: mongodb-headless
    selector:
        matchLabels:
            project: roboshop
            tier: database
            service: mongodb
    template:
        metadata:
            labels:
                project: roboshop
                tier: database
                service: mongodb
        spec:
            containers:
                - name: mongodb
                  image: "{{ .Values.statefulset.imageRepo }}:{{ .Values.statefulset.imageVersion }}"
                  imagePullPolicy: Always
                  volumeMounts:
                    - name: mongodb
                      mountPath: /data/db
    volumeClaimTemplates: 
        - metadata: 
            name: mongodb
          spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "roboshop-ebs-sc"
          resources:
          requests:
            storage: 1Gi