apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: redis
    namespace: roboshop
    labels:
        project: roboshop
        tier: database
        service: redis
spec:
    replicas: 1
    serviceName: redis-headless
    selector:
        matchLabels:
            project: roboshop
            tier: database
            service: redis
    template:
        metadata:
            labels:
                project: roboshop
                tier: database
                service: redis
        spec:
            containers:
                - name: redis
                  image: "{{ .Values.statefulset.imageRepo }}:{{ .Values.statefulset.imageVersion }}"
                  imagePullPolicy: Always
                  volumeMounts:
                    - name: redis
                      mountPath: /data
    volumeClaimTemplates:
        - metadata:
            name: redis
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "roboshop-ebs-sc"
            resources:
                requests:
                    storage: 1Gi