apiVersion: apps/v1
kind: Deployment
metadata:
    name: shipping
    namespace: roboshop
    labels:
        project: roboshop
        tier: backend
        service: shipping
spec:
    replicas: 1
    selector:
        matchLabels:
            project: roboshop
            tier: backend
            service: shipping
    template:
        metadata:
            labels:
                project: roboshop
                tier: backend
                service: shipping
        spec:
            containers:
              - name: shipping
                image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion }}"
                imagePullPolicy: Always
                envFrom:
                  - configMapRef:
                        name: shipping
                livenessProbe:
                    httpGet:
                        path: /health
                        port: 8080
                    initialDelaySeconds: 200
                    periodSeconds: 10
                readinessProbe:
                    httpGet:
                        path: /health
                        port: 8080
                    initialDelaySeconds: 20
                    periodSeconds: 10
                    failureThreshold: 3
                resources:
                    limits:
                        memory: "384Mi"
                        cpu: "500m"
                    requests:
                        memory: "128Mi"
                        cpu: "250m"