apiVersion: v1
kind: Service
metadata:
    name: frontend
    namespace: roboshop
    labels:
        project: roboshop
        tier: frontend
        service: frontend
spec:
    type: LoadBalancer
    selector:
        project: roboshop
        tier: frontend
        service: frontend
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080